version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - API_HOST=app
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "5005:80"

  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=postgres
    ports:
      - "54321:5432"

volumes:
  postgres_data: